
/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXW236
package_id: MCXW236BIHNAR
mcu_data: ksdk2_0
processor_version: 0.0.0
external_user_signals: {}
pin_labels:
- {pin_num: '7', pin_signal: PIO0_19/FC2_TXD_SCL_MISO/SCT_GPI0/PLU_OUT7/SEC_PIO0_19/CTIMER4_MAT3/CTIMER_INP19, label: LED_BLUE, identifier: LED_BLUE;RED}
- {pin_num: '31', pin_signal: PIO0_0/FC0_CTS_SDA_SSEL0/FC1_RTS_SCL_SSEL1/SEC_PIO0_0/CTIMER0_MAT0/CTIMER_INP0, label: RGB_GREEN, identifier: RGB_RED;GREEN;RGB_GREEN}
- {pin_num: '4', pin_signal: PIO0_4/FC0_SCK/SCT_OUT7/SEC_PIO0_4/CTIMER1_MAT0/CTIMER_INP4, label: RGB_BLUE, identifier: RGB_BLUE}
- {pin_num: '1', pin_signal: PIO0_1/FC0_RTS_SCL_SSEL1/FC2_SCK/PLU_CLKIN/SEC_PIO0_1/CTIMER0_MAT1/CTIMER_INP1, label: RGB_RED, identifier: RGB_RED}
- {pin_num: '8', pin_signal: PIO0_18/FC2_RXD_SDA_MOSI/SCT_GPI1/CLKOUT/PLU_OUT6/SEC_PIO0_18/CTIMER4_MAT2/CTIMER_INP18, label: BUTTON0, identifier: BUTTON0}
- {pin_num: '14', pin_signal: PIO0_21/WAKEUP/SEC_PIO0_21/CTIMER_INP21, label: BUTTON1, identifier: BUTTON1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    I2C1_InitPins();
    SPI1_InitPins();
    USART0_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_3/FC0_TXD_SCL_MISO/SCT_OUT8/FREQME_GPIO_3/SEC_PIO0_3/CTIMER0_MAT3/CTIMER_INP3, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '2', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI/SCT_OUT9/SEC_PIO0_2/CTIMER0_MAT2/CTIMER_INP2, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '7', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/FC2_TXD_SCL_MISO/SCT_GPI0/PLU_OUT7/SEC_PIO0_19/CTIMER4_MAT3/CTIMER_INP19, identifier: LED_BLUE,
    direction: OUTPUT, gpio_init_state: 'true', mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '1', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/FC0_RTS_SCL_SSEL1/FC2_SCK/PLU_CLKIN/SEC_PIO0_1/CTIMER0_MAT1/CTIMER_INP1, direction: OUTPUT,
    gpio_init_state: 'true', mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '31', peripheral: GPIO, signal: 'PIO0, 0', pin_signal: PIO0_0/FC0_CTS_SDA_SSEL0/FC1_RTS_SCL_SSEL1/SEC_PIO0_0/CTIMER0_MAT0/CTIMER_INP0, identifier: RGB_GREEN,
    direction: OUTPUT, gpio_init_state: 'true', mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/FC0_SCK/SCT_OUT7/SEC_PIO0_4/CTIMER1_MAT0/CTIMER_INP4, direction: OUTPUT, gpio_init_state: 'true',
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '8', peripheral: GPIO, signal: 'PIO0, 18', pin_signal: PIO0_18/FC2_RXD_SDA_MOSI/SCT_GPI1/CLKOUT/PLU_OUT6/SEC_PIO0_18/CTIMER4_MAT2/CTIMER_INP18, direction: INPUT,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '14', peripheral: GPIO, signal: 'PIO0, 21', pin_signal: PIO0_21/WAKEUP/SEC_PIO0_21/CTIMER_INP21, direction: INPUT, mode: inactive, slew_rate: standard,
    invert: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t RGB_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_0 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_RGB_GREEN_GPIO, BOARD_INITPINS_RGB_GREEN_PORT, BOARD_INITPINS_RGB_GREEN_PIN, &RGB_GREEN_config);

    gpio_pin_config_t RGB_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_1 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_RGB_RED_GPIO, BOARD_INITPINS_RGB_RED_PORT, BOARD_INITPINS_RGB_RED_PIN, &RGB_RED_config);

    gpio_pin_config_t RGB_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_RGB_BLUE_GPIO, BOARD_INITPINS_RGB_BLUE_PORT, BOARD_INITPINS_RGB_BLUE_PIN, &RGB_BLUE_config);

    gpio_pin_config_t BUTTON0_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_18 (pin 8)  */
    GPIO_PinInit(BOARD_INITPINS_BUTTON0_GPIO, BOARD_INITPINS_BUTTON0_PORT, BOARD_INITPINS_BUTTON0_PIN, &BUTTON0_config);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin 7)  */
    GPIO_PinInit(BOARD_INITPINS_LED_BLUE_GPIO, BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, &LED_BLUE_config);

    gpio_pin_config_t BUTTON1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_21 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_BUTTON1_GPIO, BOARD_INITPINS_BUTTON1_PORT, BOARD_INITPINS_BUTTON1_PIN, &BUTTON1_config);

    const uint32_t RGB_GREEN = (/* Pin is configured as PIO0_0 */
                                IOCON_PIO_FUNC0 |
                                /* No addition pin function */
                                IOCON_PIO_MODE_INACT |
                                /* Standard mode, output slew rate control is enabled */
                                IOCON_PIO_SLEW_STANDARD |
                                /* Input function is not inverted */
                                IOCON_PIO_INV_DI |
                                /* Enables digital function */
                                IOCON_PIO_DIGITAL_EN |
                                /* Open drain is disabled */
                                IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN0 (coords: 31) is configured as PIO0_0 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_RGB_GREEN_PORT, BOARD_INITPINS_RGB_GREEN_PIN, RGB_GREEN);

    const uint32_t RGB_RED = (/* Pin is configured as PIO0_1 */
                              IOCON_PIO_FUNC0 |
                              /* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Standard mode, output slew rate control is enabled */
                              IOCON_PIO_SLEW_STANDARD |
                              /* Input function is not inverted */
                              IOCON_PIO_INV_DI |
                              /* Enables digital function */
                              IOCON_PIO_DIGITAL_EN |
                              /* Open drain is disabled */
                              IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN1 (coords: 1) is configured as PIO0_1 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_RGB_RED_PORT, BOARD_INITPINS_RGB_RED_PIN, RGB_RED);

    const uint32_t BUTTON0 = (/* Pin is configured as PIO0_18 */
                              IOCON_PIO_FUNC0 |
                              /* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Standard mode, output slew rate control is enabled */
                              IOCON_PIO_SLEW_STANDARD |
                              /* Input function is not inverted */
                              IOCON_PIO_INV_DI |
                              /* Enables digital function */
                              IOCON_PIO_DIGITAL_EN |
                              /* Open drain is disabled */
                              IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN18 (coords: 8) is configured as PIO0_18 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_BUTTON0_PORT, BOARD_INITPINS_BUTTON0_PIN, BUTTON0);

#if defined(gAppUseSerialManager_c) && (gAppUseSerialManager_c > 1)
    /* Use pin 19 for UART prints */
      const uint32_t port0_pin19_config = (/* Pin is configured as FC2_TXD_SCL_MISO */
                                          IOCON_PIO_FUNC1 |
                                          /* No addition pin function */
                                          IOCON_PIO_MODE_INACT |
                                          /* Standard mode, output slew rate control is enabled */
                                          IOCON_PIO_SLEW_STANDARD |
                                          /* Input function is not inverted */
                                          IOCON_PIO_INV_DI |
                                          /* Enables digital function */
                                          IOCON_PIO_DIGITAL_EN |
                                          /* Open drain is disabled */
                                          IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN19 (coords: 7) is configured as FC2_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 19U, port0_pin19_config);
#else
    /* Use pin 19 for blue LED */
    const uint32_t LED_BLUE = (/* Pin is configured as PIO0_19 */
                               IOCON_PIO_FUNC0 |
                               /* No addition pin function */
                               IOCON_PIO_MODE_INACT |
                               /* Standard mode, output slew rate control is enabled */
                               IOCON_PIO_SLEW_STANDARD |
                               /* Input function is not inverted */
                               IOCON_PIO_INV_DI |
                               /* Enables digital function */
                               IOCON_PIO_DIGITAL_EN |
                               /* Open drain is disabled */
                               IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN19 (coords: 7) is configured as PIO0_19 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, LED_BLUE);
#endif /* defined(gAppUseSerialManager_c) && (gAppUseSerialManager_c >= 1) */

    const uint32_t port0_pin2_config = (/* Pin is configured as FC0_RXD_SDA_MOSI */
                                        IOCON_PIO_FUNC1 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN2 (coords: 2) is configured as FC0_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 2U, port0_pin2_config);

    const uint32_t BUTTON1 = (/* Pin is configured as PIO0_21 */
                              IOCON_PIO_FUNC0 |
                              /* No addition pin function */
                              IOCON_PIO_MODE_INACT |
                              /* Standard mode, output slew rate control is enabled */
                              IOCON_PIO_SLEW_STANDARD |
                              /* Input function is not inverted */
                              IOCON_PIO_INV_DI |
                              /* Enables digital function */
                              IOCON_PIO_DIGITAL_EN |
                              /* Open drain is disabled */
                              IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN21 (coords: 14) is configured as PIO0_21 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_BUTTON1_PORT, BOARD_INITPINS_BUTTON1_PIN, BUTTON1);

    const uint32_t port0_pin3_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                        IOCON_PIO_FUNC1 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN3 (coords: 3) is configured as FC0_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 3U, port0_pin3_config);

    const uint32_t RGB_BLUE = (/* Pin is configured as PIO0_4 */
                               IOCON_PIO_FUNC0 |
                               /* No addition pin function */
                               IOCON_PIO_MODE_INACT |
                               /* Standard mode, output slew rate control is enabled */
                               IOCON_PIO_SLEW_STANDARD |
                               /* Input function is not inverted */
                               IOCON_PIO_INV_DI |
                               /* Enables digital function */
                               IOCON_PIO_DIGITAL_EN |
                               /* Open drain is disabled */
                               IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN4 (coords: 4) is configured as PIO0_4 */
    IOCON_PinMuxSet(IOCON, BOARD_INITPINS_RGB_BLUE_PORT, BOARD_INITPINS_RGB_BLUE_PIN, RGB_BLUE);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
I2C1_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: FLEXCOMM1, signal: RXD_SDA_MOSI, pin_signal: PIO0_13/FC1_RXD_SDA_MOSI/FC2_CTS_SDA_SSEL0/SCT_OUT2/UTICK_CAP2/PLU_OUT1/SEC_PIO0_13/CTIMER3_MAT1/CTIMER_INP13,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
  - {pin_num: '5', peripheral: FLEXCOMM1, signal: TXD_SCL_MISO, pin_signal: PIO0_14/FC1_TXD_SCL_MISO/FC2_RTS_SCL_SSEL1/SCT_OUT1/FREQME_GPIO_14/UTICK_CAP3/PLU_OUT2/SEC_PIO0_14/CTIMER3_MAT2/CTIMER_INP14,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void I2C1_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin13_config = (/* Pin is configured as FC1_RXD_SDA_MOSI */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN13 (coords: 6) is configured as FC1_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 13U, port0_pin13_config);

    const uint32_t port0_pin14_config = (/* Pin is configured as FC1_TXD_SCL_MISO */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN14 (coords: 5) is configured as FC1_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 14U, port0_pin14_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
I2C1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/FC1_RXD_SDA_MOSI/FC2_CTS_SDA_SSEL0/SCT_OUT2/UTICK_CAP2/PLU_OUT1/SEC_PIO0_13/CTIMER3_MAT1/CTIMER_INP13,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/FC1_TXD_SCL_MISO/FC2_RTS_SCL_SSEL1/SCT_OUT1/FREQME_GPIO_14/UTICK_CAP3/PLU_OUT2/SEC_PIO0_14/CTIMER3_MAT2/CTIMER_INP14,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void I2C1_DeinitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin13_config = (/* Pin is configured as PIO0_13 */
                                         IOCON_PIO_FUNC0 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN13 (coords: 6) is configured as PIO0_13 */
    IOCON_PinMuxSet(IOCON, 0U, 13U, port0_pin13_config);

    const uint32_t port0_pin14_config = (/* Pin is configured as PIO0_14 */
                                         IOCON_PIO_FUNC0 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN14 (coords: 5) is configured as PIO0_14 */
    IOCON_PinMuxSet(IOCON, 0U, 14U, port0_pin14_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI1_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '31', peripheral: FLEXCOMM1, signal: RTS_SCL_SSEL1, pin_signal: PIO0_0/FC0_CTS_SDA_SSEL0/FC1_RTS_SCL_SSEL1/SEC_PIO0_0/CTIMER0_MAT0/CTIMER_INP0, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '6', peripheral: FLEXCOMM1, signal: RXD_SDA_MOSI, pin_signal: PIO0_13/FC1_RXD_SDA_MOSI/FC2_CTS_SDA_SSEL0/SCT_OUT2/UTICK_CAP2/PLU_OUT1/SEC_PIO0_13/CTIMER3_MAT1/CTIMER_INP13,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
  - {pin_num: '32', peripheral: FLEXCOMM1, signal: SCK, pin_signal: PIO0_16/FC1_SCK/SCT_GPI3/PLU_OUT4/SEC_PIO0_16/ANT_SWITCH_1/CTIMER4_MAT0/CTIMER_INP16, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '5', peripheral: FLEXCOMM1, signal: TXD_SCL_MISO, pin_signal: PIO0_14/FC1_TXD_SCL_MISO/FC2_RTS_SCL_SSEL1/SCT_OUT1/FREQME_GPIO_14/UTICK_CAP3/PLU_OUT2/SEC_PIO0_14/CTIMER3_MAT2/CTIMER_INP14,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void SPI1_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin0_config = (/* Pin is configured as FC1_RTS_SCL_SSEL1 */
                                        IOCON_PIO_FUNC2 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN0 (coords: 31) is configured as FC1_RTS_SCL_SSEL1 */
    IOCON_PinMuxSet(IOCON, 0U, 0U, port0_pin0_config);

    const uint32_t port0_pin13_config = (/* Pin is configured as FC1_RXD_SDA_MOSI */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN13 (coords: 6) is configured as FC1_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 13U, port0_pin13_config);

    const uint32_t port0_pin14_config = (/* Pin is configured as FC1_TXD_SCL_MISO */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN14 (coords: 5) is configured as FC1_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 14U, port0_pin14_config);

    const uint32_t port0_pin16_config = (/* Pin is configured as FC1_SCK */
                                         IOCON_PIO_FUNC2 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN16 (coords: 32) is configured as FC1_SCK */
    IOCON_PinMuxSet(IOCON, 0U, 16U, port0_pin16_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/FC1_RXD_SDA_MOSI/FC2_CTS_SDA_SSEL0/SCT_OUT2/UTICK_CAP2/PLU_OUT1/SEC_PIO0_13/CTIMER3_MAT1/CTIMER_INP13,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/FC1_TXD_SCL_MISO/FC2_RTS_SCL_SSEL1/SCT_OUT1/FREQME_GPIO_14/UTICK_CAP3/PLU_OUT2/SEC_PIO0_14/CTIMER3_MAT2/CTIMER_INP14,
    mode: inactive, slew_rate: standard, invert: disabled, open_drain: disabled, ssel: signal3v3, filter_off: disabled, ecs: disabled, egp: gpio, i2cfilter: nonhighspeedmode}
  - {pin_num: '31', peripheral: GPIO, signal: 'PIO0, 0', pin_signal: PIO0_0/FC0_CTS_SDA_SSEL0/FC1_RTS_SCL_SSEL1/SEC_PIO0_0/CTIMER0_MAT0/CTIMER_INP0, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '32', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16/FC1_SCK/SCT_GPI3/PLU_OUT4/SEC_PIO0_16/ANT_SWITCH_1/CTIMER4_MAT0/CTIMER_INP16, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void SPI1_DeinitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin0_config = (/* Pin is configured as PIO0_0 */
                                        IOCON_PIO_FUNC0 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN0 (coords: 31) is configured as PIO0_0 */
    IOCON_PinMuxSet(IOCON, 0U, 0U, port0_pin0_config);

    const uint32_t port0_pin13_config = (/* Pin is configured as PIO0_13 */
                                         IOCON_PIO_FUNC0 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN13 (coords: 6) is configured as PIO0_13 */
    IOCON_PinMuxSet(IOCON, 0U, 13U, port0_pin13_config);

    const uint32_t port0_pin14_config = (/* Pin is configured as PIO0_14 */
                                         IOCON_PIO_FUNC0 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI |
                                         /* 3V3 signaling in I2C mode */
                                         IOCON_PIO_SSEL_3V3 |
                                         /* Input filter disabled */
                                         IOCON_PIO_INPFILT_OFF |
                                         /* IO is an open drain cell */
                                         IOCON_PIO_ECS_DI |
                                         /* GPIO mode */
                                         IOCON_PIO_EGP_GPIO |
                                         /* I2C 50 ns glitch filter enabled. Typically used for Standard mode, Fast-mode and Fast-mode Plus I2C. */
                                         IOCON_PIO_I2CFILTER_NONHIGHSPEED);
    /* PORT0 PIN14 (coords: 5) is configured as PIO0_14 */
    IOCON_PinMuxSet(IOCON, 0U, 14U, port0_pin14_config);

    const uint32_t port0_pin16_config = (/* Pin is configured as PIO0_16 */
                                         IOCON_PIO_FUNC0 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN16 (coords: 32) is configured as PIO0_16 */
    IOCON_PinMuxSet(IOCON, 0U, 16U, port0_pin16_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
USART0_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '2', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI/SCT_OUT9/SEC_PIO0_2/CTIMER0_MAT2/CTIMER_INP2, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
  - {pin_num: '3', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_3/FC0_TXD_SCL_MISO/SCT_OUT8/FREQME_GPIO_3/SEC_PIO0_3/CTIMER0_MAT3/CTIMER_INP3, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : USART0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void USART0_InitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin2_config = (/* Pin is configured as FC0_RXD_SDA_MOSI */
                                        IOCON_PIO_FUNC1 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN2 (coords: 2) is configured as FC0_RXD_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 2U, port0_pin2_config);

    const uint32_t port0_pin3_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
                                        IOCON_PIO_FUNC1 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN3 (coords: 3) is configured as FC0_TXD_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 3U, port0_pin3_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
USART0_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 2', pin_signal: PIO0_2/FC0_RXD_SDA_MOSI/SCT_OUT9/SEC_PIO0_2/CTIMER0_MAT2/CTIMER_INP2, mode: inactive, slew_rate: standard,
    invert: disabled, open_drain: disabled}
  - {pin_num: '3', peripheral: GPIO, signal: 'PIO0, 3', pin_signal: PIO0_3/FC0_TXD_SCL_MISO/SCT_OUT8/FREQME_GPIO_3/SEC_PIO0_3/CTIMER0_MAT3/CTIMER_INP3, mode: inactive,
    slew_rate: standard, invert: disabled, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : USART0_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void USART0_DeinitPins(void)
{
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);

    const uint32_t port0_pin2_config = (/* Pin is configured as PIO0_2 */
                                        IOCON_PIO_FUNC0 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN2 (coords: 2) is configured as PIO0_2 */
    IOCON_PinMuxSet(IOCON, 0U, 2U, port0_pin2_config);

    const uint32_t port0_pin3_config = (/* Pin is configured as PIO0_3 */
                                        IOCON_PIO_FUNC0 |
                                        /* No addition pin function */
                                        IOCON_PIO_MODE_INACT |
                                        /* Standard mode, output slew rate control is enabled */
                                        IOCON_PIO_SLEW_STANDARD |
                                        /* Input function is not inverted */
                                        IOCON_PIO_INV_DI |
                                        /* Enables digital function */
                                        IOCON_PIO_DIGITAL_EN |
                                        /* Open drain is disabled */
                                        IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN3 (coords: 3) is configured as PIO0_3 */
    IOCON_PinMuxSet(IOCON, 0U, 3U, port0_pin3_config);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/